"""Judge rubric data: per-phase scoring dimensions (data only, no logic)."""

from __future__ import annotations

from typing import Any, Final

# Phase → 评审维度定义（1-5 Likert 量表，每级有明确标准）
JUDGE_RUBRICS: Final[dict[str, dict[str, Any]]] = {
    "Q01": {
        "name": "需求结构化",
        "dimensions": [
            {
                "id": "faithfulness",
                "name": "忠实度",
                "description": "输出的 REQ/SE/GAP 是否忠实于 PRD 原文，不编造",
                "weight": 0.25,
                "rubric": {
                    5: "所有 REQ/SE/GAP 都能在 PRD 原文中找到明确依据",
                    4: "90%+ 有依据，少量合理推断已标注置信度",
                    3: "70-90% 有依据，部分推断未标注",
                    2: "50-70% 有依据，存在明显编造内容",
                    1: "大量内容无法在 PRD 中找到依据",
                },
            },
            {
                "id": "completeness",
                "name": "完备性",
                "description": "PRD 中的所有需求点是否都被提取为 REQ/BR",
                "weight": 0.3,
                "rubric": {
                    5: "PRD 所有功能点、业务规则、约束条件均已提取，无遗漏",
                    4: "核心功能点全部覆盖，仅遗漏 1-2 个边缘场景",
                    3: "主要功能点已覆盖，遗漏 3-5 个需求点",
                    2: "明显遗漏多个功能点或整个业务模块",
                    1: "大面积遗漏，仅提取了部分表面需求",
                },
            },
            {
                "id": "se_explicitness",
                "name": "SE 显式率",
                "description": "关键业务语义是否都被显式化为可验证的 SE",
                "weight": 0.25,
                "rubric": {
                    5: "每个 REQ/BR 都有对应的可验证 SE，隐式语义全部显式化",
                    4: "90%+ REQ 有对应 SE，少量隐式语义未提取",
                    3: "70-90% 有 SE，并发/幂等/边界等隐式语义部分遗漏",
                    2: "SE 覆盖不足 70%，大量业务语义隐含在 REQ 描述中",
                    1: "几乎没有 SE，或 SE 与 REQ 重复无新增信息",
                },
            },
            {
                "id": "gap_detection",
                "name": "GAP 发现率",
                "description": "PRD 中的模糊点、缺失定义是否被识别为 GAP",
                "weight": 0.2,
                "rubric": {
                    5: "所有模糊描述、缺失定义、歧义点均已识别为 GAP/OPEN",
                    4: "主要模糊点已识别，仅遗漏 1-2 个非关键 GAP",
                    3: "识别了部分 GAP，但遗漏了并发/幂等/安全等关键缺口",
                    2: "GAP 识别明显不足，多个关键缺口未发现",
                    1: "几乎未识别 GAP，或 GAP 为 0 但 PRD 明显有模糊点",
                },
            },
        ],
    },
    "Q04": {
        "name": "技术方案覆盖度审计",
        "dimensions": [
            {
                "id": "coverage_accuracy",
                "name": "覆盖判定准确率",
                "description": "COVERED/PARTIAL/MISSING/IMPLICIT 的判定是否正确",
                "weight": 0.4,
                "rubric": {
                    5: "所有覆盖状态判定正确，COVERED 确实有完整设计，MISSING 确实缺失",
                    4: "90%+ 判定正确，个别 PARTIAL/COVERED 边界有争议",
                    3: "70-90% 正确，存在将仅提到接口名就判为 COVERED 的情况",
                    2: "多个判定错误，正向流程有但异常分支缺失仍判为 COVERED",
                    1: "大面积判定错误，覆盖率虚高",
                },
            },
            {
                "id": "missing_detection",
                "name": "遗漏检出率",
                "description": "技术方案中真正缺失的需求点是否被标记为 MISSING",
                "weight": 0.3,
                "rubric": {
                    5: "所有缺失的需求点都被准确标记为 MISSING",
                    4: "核心缺失全部检出，仅遗漏 1-2 个边缘 MISSING",
                    3: "检出了部分 MISSING，但遗漏了关键异常处理/并发场景的缺失",
                    2: "MISSING 检出不足，多个关键缺失未发现",
                    1: "几乎未检出 MISSING，或全部标为 COVERED",
                },
            },
            {
                "id": "reverse_audit",
                "name": "反向审计完整性",
                "description": "技术方案中的新增设计是否被标记为 NEW_DESIGN/NOT_IN_SCOPE",
                "weight": 0.3,
                "rubric": {
                    5: "技术方案中所有超出 PRD 范围的设计都被识别并标记",
                    4: "主要新增设计已识别，仅遗漏 1-2 个",
                    3: "部分新增设计被识别，但遗漏了重要的范围外设计",
                    2: "反向审计明显不足",
                    1: "未做反向审计",
                },
            },
        ],
    },
    "Q03": {
        "name": "技术方案质量评审",
        "dimensions": [
            {
                "id": "issue_validity",
                "name": "问题有效率",
                "description": "发现的质量问题是否是真问题（非噪音）",
                "weight": 0.25,
                "rubric": {
                    5: "所有 issue 都是真问题，有具体代码/设计证据支撑",
                    4: "90%+ 是真问题，个别 issue 证据稍弱",
                    3: "70-90% 是真问题，存在噪音 issue",
                    2: "噪音 issue 占比超 30%",
                    1: "大量噪音，issue 缺乏证据",
                },
            },
            {
                "id": "failure_mode_coverage",
                "name": "Failure Mode 覆盖率",
                "description": "关键业务路径是否都做了故障场景分析",
                "weight": 0.25,
                "rubric": {
                    5: "所有写操作/RPC 调用/状态迁移都有 Failure Mode 分析",
                    4: "核心路径全覆盖，仅遗漏 1-2 个非关键路径",
                    3: "主要路径已覆盖，但跨服务调用的部分失败场景遗漏",
                    2: "Failure Mode 分析不完整，多个关键路径缺失",
                    1: "几乎未做 Failure Mode 分析",
                },
            },
            {
                "id": "exception_coverage",
                "name": "异常矩阵覆盖率",
                "description": "异常分类目录中的类型是否都被检查",
                "weight": 0.3,
                "rubric": {
                    5: "9 类异常分支全部检查，每类有具体的技术方案对应分析",
                    4: "7-8 类已检查，仅遗漏 1-2 个低频异常类型",
                    3: "5-6 类已检查，遗漏了 E-CONFLICT/E-TIMEOUT 等关键类型",
                    2: "检查不足 5 类",
                    1: "几乎未对照异常矩阵检查",
                },
            },
            {
                "id": "se_verifiability",
                "name": "SE 可验证性",
                "description": "上游 Phase A 生成的 SE 是否有明确的验证标准，而非模糊描述",
                "weight": 0.2,
                "rubric": {
                    5: "所有 SE 都有可执行的验证条件（输入→预期输出），可直接转化为测试用例",
                    4: "90%+ SE 可验证，少量需要补充边界条件",
                    3: "70-90% 可验证，部分 SE 过于抽象（如'性能要好'）",
                    2: "50-70% 可验证，多个 SE 是模糊描述无法转化为测试",
                    1: "大量 SE 无法转化为具体测试用例，缺少输入输出定义",
                },
            },
        ],
    },
    "Q06": {
        "name": "单测覆盖审计",
        "dimensions": [
            {
                "id": "audit_accuracy",
                "name": "审计判定准确率",
                "description": "COVERED/MISSING/WRONG_TARGET 的判定是否正确。严禁从 BUG_CASES 历史案例推断当前报告存在同类问题——BUG_CASES 是已修正的历史错误，不是当前审计的缺陷；EUT ID 是否存在于 Q05 必须从实际文件验证，不能靠历史案例推断",
                "weight": 0.35,
                "rubric": {
                    5: "所有审计状态判定正确，COVERED 确实有强断言，WRONG_TARGET 确实是弱断言，无漏报；EUT ID 引用验证充分",
                    4: "90%+ 判定正确，无明显弱断言漏报，PARTIAL 有充分技术理由，MISSING 仅限私有辅助方法——整体质量良好，应给 PASS_WITH_CONCERNS；不能因 BUG_CASES 提到某 EUT ID 就推断当前报告存在 EUT ID 问题",
                    3: "70-90% 正确，有可验证的弱断言漏报（必须有原文引用，不能推断）——此分数代表有完整审计报告但存在部分缺陷，应给 PASS_WITH_CONCERNS",
                    2: "报告内容极不完整或大面积判定错误（需要多处具体原文引用证明，不接受 BUG_CASES 推断或假设性陈述）",
                    1: "报告不存在或仅为错误消息/验证失败信息，无实质审计内容",
                },
            },
            {
                "id": "wrong_target_detection",
                "name": "WRONG_TARGET 检出率",
                "description": "弱断言是否被识别（三种合格形式：① WRONG_TARGET 显式标记；② PARTIAL+说明；③ 报告头部汇总统计明确列出弱断言数量）",
                "weight": 0.3,
                "rubric": {
                    5: "所有弱断言都被识别：通过 WRONG_TARGET 标记、PARTIAL 分类或报告头部统计（如'仅弱断言 assertNotNull-only: N 个'）明确列出；若报告本身无弱断言则直接给 5 分",
                    4: "弱断言已在报告中通过任意形式识别（头部统计、WRONG_TARGET、PARTIAL），整体识别率 90%+——报告明确给出弱断言数量统计即符合此标准，应给 PASS_WITH_CONCERNS",
                    3: "弱断言识别不完整，但报告有完整内容——此分数代表有审计报告但弱断言识别方式不够规范，应给 PASS_WITH_CONCERNS",
                    2: "报告内容极少或不完整，无实质弱断言识别记录（若报告有任何弱断言数量统计，则此维度至少 4 分）",
                    1: "报告不存在或仅为错误消息，无任何弱断言检查",
                },
            },
            {
                "id": "exception_branch",
                "name": "异常分支覆盖",
                "description": "T1 核心公共业务方法的异常分支是否都有对应测试；私有辅助方法的 MISSING_DIRECT_TEST 不影响此维度",
                "weight": 0.25,
                "rubric": {
                    5: "所有 T1 核心公共业务方法的异常分支都有测试，断言验证异常类型（assertThrows）+业务状态不变+无脏数据；若项目无 T1 并发/幂等场景则不扣分",
                    4: "T1 核心公共业务方法的异常分支全部有测试，assertThrows 验证正确异常类型；私有辅助方法未直接测试不影响此维度评分——此分数说明异常覆盖充分，应给 PASS_WITH_CONCERNS",
                    3: "主要 T1 公共业务方法有测试，但有 1-2 个 T1 核心公共方法（如非法状态跳转、版本冲突业务逻辑）缺少异常测试",
                    2: "T1 核心公共业务方法的异常测试明显缺失（3 个以上公共方法无测试），只有 happy path",
                    1: "几乎无异常分支测试，或全是 happy path 无任何异常场景",
                },
            },
            {
                "id": "scenario_quality",
                "name": "场景覆盖质量",
                "description": "测试数据是否覆盖真实故障组合（多记录/边界值/特定枚举组合/多条件AND）。[判定校准] 本 Phase 的核心判定维度为 audit_accuracy/wrong_target_detection/exception_branch/scenario_quality 四项；动态维度（dyn_* 前缀）是补充参考，不应单独决定 PASS/FAIL——当四项核心维度均 >= 3 分且无明确 FAIL 触发点时，应给 PASS_WITH_CONCERNS",
                "weight": 0.1,
                "rubric": {
                    5: "测试数据覆盖了多记录场景、边界值组合、特定枚举组合，mock 数据贴近真实业务字段",
                    4: "主要场景已覆盖，mock 数据包含真实枚举值和核心字段，个别边界组合缺失——此为可接受的覆盖质量",
                    3: "测试数据偏简单（单记录、默认值），未覆盖多条件组合触发的分支",
                    2: "测试数据明显不足，多个关键组合未覆盖",
                    1: "测试数据几乎全是 happy path 默认值，无法触发真实故障路径",
                },
            },
        ],
    },
    "Q05": {
        "name": "单测生成",
        "dimensions": [
            {
                "id": "eut_coverage",
                "name": "EUT 覆盖完备性",
                "description": "EUT 矩阵是否覆盖了所有 REQ/BR/SE，包括 Happy Path、Exception、Boundary",
                "weight": 0.3,
                "rubric": {
                    5: "每条 REQ/BR/SE 都有对应 EUT，三种路径类型均覆盖",
                    4: "90%+ REQ/SE 有 EUT，仅遗漏 1-2 个边界场景",
                    3: "主要 REQ 有 EUT，但 Exception/Boundary 路径覆盖不足",
                    2: "EUT 覆盖不足 70%，大量 SE 无对应测试",
                    1: "EUT 矩阵严重不完整",
                },
            },
            {
                "id": "assert_strength",
                "name": "断言强度",
                "description": "生成的单测是否使用强断言验证业务语义，而非仅 assertNotNull/assertTrue(true)",
                "weight": 0.35,
                "rubric": {
                    5: "所有测试都有 assertEquals 验证业务字段、verify 验证交互、assertThrows 验证异常码",
                    4: "90%+ 测试有强断言，个别测试断言稍弱",
                    3: "主要测试有强断言，但存在 assertNotNull 冒充覆盖的情况",
                    2: "多个测试仅有弱断言，未验证业务语义",
                    1: "大量测试无实质断言或仅 assertNotNull",
                },
            },
            {
                "id": "code_compilability",
                "name": "代码可编译性",
                "description": "生成的单测代码是否能通过编译，import/mock/setup 是否正确",
                "weight": 0.2,
                "rubric": {
                    5: "所有测试代码编译通过，import 正确，mock 配置完整",
                    4: "90%+ 编译通过，个别 import 缺失但易修复",
                    3: "主要测试可编译，但 mock 配置有遗漏导致部分编译失败",
                    2: "多个测试编译失败，缺少关键依赖或 mock",
                    1: "大面积编译失败",
                },
            },
            {
                "id": "se_traceability",
                "name": "SE 追溯性",
                "description": "每个测试方法是否能追溯到对应的 SE/EUT ID",
                "weight": 0.15,
                "rubric": {
                    5: "每个 @Test 方法都有 @Tag 或注释标注对应的 EUT/SE ID",
                    4: "90%+ 测试有追溯标注",
                    3: "部分测试有标注，但缺少系统性的追溯",
                    2: "追溯标注不足 50%",
                    1: "几乎无追溯标注",
                },
            },
        ],
    },
    "Q05a": {
        "name": "EUT 矩阵设计",
        "dimensions": [
            {
                "id": "req_coverage",
                "name": "需求覆盖完备性",
                "description": "EUT 矩阵是否覆盖了所有 REQ/BR/SE，每条需求都有对应的 EUT 条目。铁律：每条 EUT 的 bound_item 只能绑定单个 SE/BR/REQ；将多个 SE 合并为一条 EUT 是 SE-based 聚合模式，属于铁律违反，直接导致 FAIL",
                "weight": 0.30,
                "rubric": {
                    5: "每条 REQ、BR、SE 都有至少一个对应 EUT，bound_item 字段引用准确，无 SE-based 聚合",
                    4: "90%+ REQ/BR/SE 有对应 EUT，仅遗漏 1-2 个非关键语义点，无 SE-based 聚合——整体覆盖良好，应给 PASS_WITH_CONCERNS",
                    3: "主要 REQ/BR 有覆盖，但 SE（隐式语义）遗漏超过 3 条",
                    2: "EUT 覆盖不足 70%，整块 BR 或 SE 类型无对应测试",
                    1: "EUT 矩阵严重不完整或存在 SE-based 聚合（多个 SE 绑定同一 EUT，路径类型为 Mixed）",
                },
            },
            {
                "id": "code_path_projection",
                "name": "代码路径覆盖投影",
                "description": "EUT 矩阵对目标类的 Happy/Exception/Boundary/Concurrent 路径是否达到 100% 投影覆盖。每条 EUT 的路径类型必须为 Happy/Exception/Boundary/Concurrent 之一；'Mixed' 类型表示 SE-based 聚合，视为路径未分类，不计入有效覆盖",
                "weight": 0.30,
                "rubric": {
                    5: "所有目标类的 Happy/Exception/Boundary 路径均有 EUT 覆盖，并发/幂等语义存在时也已覆盖，无 Mixed 路径类型",
                    4: "Happy+Exception 路径全覆盖，Boundary 仅遗漏 1-2 个非关键边界条件——整体路径投影良好，应给 PASS_WITH_CONCERNS",
                    3: "Happy Path 全覆盖，但 Exception 或 Boundary 路径存在系统性遗漏",
                    2: "Exception/Boundary 路径覆盖不足 70%，多个异常分支无对应 EUT，或存在 Mixed 类型导致路径未分类",
                    1: "仅有 Happy Path EUT，异常和边界路径基本未覆盖，或报告无实质路径分析",
                },
            },
            {
                "id": "assertion_quality",
                "name": "断言描述质量",
                "description": "EUT 的 then 字段是否包含具体可验证的断言语义，禁止'验证接口正确'类泛化描述",
                "weight": 0.25,
                "rubric": {
                    5: "所有 EUT 的 then 包含具体断言（assertEquals(200, status)/verify(repo, times(1))/assertThrows(ExceptionClass.class, ...)），无泛化描述",
                    4: "90%+ then 字段是具体断言，个别条目描述稍泛化但含关键字段名——整体断言质量良好，应给 PASS_WITH_CONCERNS",
                    3: "主要 EUT 有具体断言，但存在 10-30% 「验证返回正确」类空话，无法直接转为代码",
                    2: "超过 30% 的 then 字段是无法直接转换为代码的泛化描述",
                    1: "大量 then 为「验证功能正常」类无效描述，或报告仅为验证错误/错误消息，无实质断言规格",
                },
            },
            {
                "id": "git_diff_coverage",
                "name": "git diff 变更覆盖",
                "description": "feature branch 新增/修改的每个实现类是否都出现在至少一条 EUT 的 when 字段中",
                "weight": 0.15,
                "rubric": {
                    5: "git diff 变更的所有实现类均出现在 EUT 的 when 字段，无漏测变更",
                    4: "90%+ 变更类有 EUT 覆盖，仅遗漏 1 个无业务语义的辅助类——整体变更覆盖充分，应给 PASS_WITH_CONCERNS",
                    3: "主要业务类有 EUT 覆盖，但存在未被 REQ/SE 引用的变更类未添加 EUT",
                    2: "超过 3 个变更类无对应 EUT，code_repo 视角覆盖明显不足",
                    1: "git diff 覆盖检查未执行或大量变更类无 EUT，或报告为纯错误消息",
                },
            },
        ],
    },
    "Q05b": {
        "name": "单测代码生成",
        "dimensions": [
            {
                "id": "eut_faithfulness",
                "name": "EUT 规格忠实度",
                "description": "生成的 @Test 方法是否忠实实现 Q05a EUT 矩阵中的 when/then 规格，不越权修改 EUT 定义。铁律：Q05b 禁止修改 EUT 矩阵；违反此铁律直接导致 FAIL",
                "weight": 0.35,
                "rubric": {
                    5: "每个 @Test 严格对应一条 EUT，when/then 与 EUT 规格一致，未修改 EUT 矩阵",
                    4: "90%+ @Test 忠实实现 EUT，个别方法对 then 做了合理技术细化（未改变语义）——整体忠实度良好，应给 PASS_WITH_CONCERNS",
                    3: "主要 @Test 符合 EUT 规格，但存在 3-5 个方法偏离 then 描述（未修改矩阵）",
                    2: "超过 20% 的 @Test 与 EUT 语义不符",
                    1: "大量 @Test 未对应 EUT 条目，或 Q05b 违规修改了 EUT 矩阵（铁律违反），或报告为错误消息",
                },
            },
            {
                "id": "assert_strength",
                "name": "断言强度",
                "description": "生成的 @Test 是否使用强断言验证业务语义，禁止 assertTrue(true)/assertNotNull 冒充覆盖。assertTrue(true) 占位符是明确的铁律违反",
                "weight": 0.30,
                "rubric": {
                    5: "所有测试使用 assertEquals/assertThrows/verify(mock,times(N)) 等强断言，无空气单测",
                    4: "90%+ 测试有强断言，无 assertTrue(true) 占位符——整体断言强度良好，应给 PASS_WITH_CONCERNS",
                    3: "主要测试有强断言，但存在 10-20% 的弱断言或仅验证非空",
                    2: "超过 20% 的测试断言不验证业务语义",
                    1: "大量测试无实质断言，或有 assertTrue(true) 占位符（铁律违反），或报告为纯错误消息",
                },
            },
            {
                "id": "compilation_correctness",
                "name": "编译正确性",
                "description": "生成的单测代码是否能通过 mvn test-compile，import/mock/setup 是否完整",
                "weight": 0.25,
                "rubric": {
                    5: "所有 @Test 编译通过，import 正确，Mockito mock 配置完整，@BeforeEach setup 正确",
                    4: "90%+ 编译通过，个别 import 遗漏但可一键修复——整体可编译，应给 PASS_WITH_CONCERNS",
                    3: "主要测试可编译，但 mock 配置不完整导致 3-5 个方法编译失败",
                    2: "超过 20% 的 @Test 编译失败，缺少关键依赖注入或 mock",
                    1: "大面积编译失败，无法运行，或报告为错误消息无实质代码",
                },
            },
            {
                "id": "ralph_loop_discipline",
                "name": "Ralph Loop 纪律",
                "description": "是否按 Ralph Loop 逐批推进（每批 3-5 条 EUT），每批编译通过后才推进，passes 状态正确更新",
                "weight": 0.10,
                "rubric": {
                    5: "严格按批次推进，每批 mvn test-compile 通过后更新 phase_b_code_status.json，passes:true 准确",
                    4: "基本按批次推进，passes 状态更新有 1-2 处延迟但最终一致——整体符合 Ralph Loop 规范",
                    3: "批次划分合理，但 passes 状态更新不及时或有遗漏",
                    2: "未按批次推进，大批量生成后统一编译，passes 状态混乱",
                    1: "未使用 Ralph Loop 模式，一次性生成所有测试代码，或报告无任何批次信息",
                },
            },
        ],
    },
    "Q07": {
        "name": "代码评审",
        "dimensions": [
            {
                "id": "finding_validity",
                "name": "发现有效率",
                "description": "评审发现的问题是否是真问题，有具体代码证据支撑",
                "weight": 0.3,
                "rubric": {
                    5: "所有 finding 都是真问题，引用了具体文件:行号和代码片段",
                    4: "90%+ 是真问题，个别 finding 证据稍弱",
                    3: "70-90% 是真问题，存在基于猜测的 finding",
                    2: "噪音 finding 占比超 30%",
                    1: "大量 finding 缺乏证据或是误报",
                },
            },
            {
                "id": "req_code_alignment",
                "name": "需求-代码对齐度",
                "description": "是否逐条检查了 REQ/BR/SE 在代码中的实现完整性",
                "weight": 0.3,
                "rubric": {
                    5: "每条 REQ/SE 都有对应的代码实现检查，缺失的明确标记为 GAP",
                    4: "90%+ REQ/SE 已检查，仅遗漏 1-2 条",
                    3: "主要 REQ 已检查，但 SE 级别的隐式语义未逐条验证",
                    2: "需求-代码对齐检查不足",
                    1: "几乎未做需求-代码对齐",
                },
            },
            {
                "id": "severity_accuracy",
                "name": "严重级别准确性",
                "description": "BLOCKER/CRITICAL/MAJOR/MINOR 的分级是否合理",
                "weight": 0.2,
                "rubric": {
                    5: "所有 finding 的严重级别准确，BLOCKER 确实会导致线上故障",
                    4: "90%+ 分级准确，个别 MAJOR/MINOR 边界有争议",
                    3: "主要分级合理，但存在将 MINOR 标为 BLOCKER 或反之的情况",
                    2: "分级明显不准确，影响修复优先级判断",
                    1: "分级混乱",
                },
            },
            {
                "id": "call_chain_tracing",
                "name": "调用链路追踪",
                "description": "是否追踪了改动功能点的完整调用链路（DDD+TMF 场景）",
                "weight": 0.2,
                "rubric": {
                    5: "所有改动点都追踪了完整调用链（Controller→Service→Domain→Gateway），跨服务调用已标注",
                    4: "核心改动点链路完整，仅遗漏 1-2 个非关键路径",
                    3: "主要链路已追踪，但跨服务/异步调用的链路不完整",
                    2: "链路追踪不足，多个改动点未追踪到 Gateway 层",
                    1: "几乎未做链路追踪",
                },
            },
        ],
    },
}

# Anti-rationalization table：防止 Judge 给虚高分数的常见借口和反驳
ANTI_RATIONALIZATION_SECTION: list[str] = [
    "",
    "## Anti-Rationalization（禁止放水）",
    "",
    "以下是 Judge 常见的放水借口。如果你发现自己在用这些理由，立即停下来重新评估。",
    "",
    "| 常见放水借口 | 为什么不能接受 | 正确做法 |",
    "|---|---|---|",
    '| "虽然缺少边界测试，但主流程覆盖了" | 边界是 bug 高发区，缺失即扣分 | 按 SE 逐条检查边界覆盖，缺失的列入 issues |',
    '| "文档描述基本清晰" | "基本"="有歧义"，必须指出哪里不清晰 | 找到具体的模糊描述，标注为 GAP |',
    '| "整体质量可接受" | 禁止整体评价，必须逐维度打分 | 每个维度独立打分，列出具体扣分证据 |',
    '| "虽然没有并发测试，但业务场景简单" | 只要 SE 涉及并发，就必须有对应验证 | 检查 SE 列表，有并发关键词的必须有测试 |',
    '| "覆盖率数字达标了" | 覆盖率不等于断言质量，assertNotNull 不算有效覆盖 | 检查断言是否验证了业务语义，不只是执行路径 |',
    '| "异常处理已经有 try-catch" | try-catch 存在不等于异常被正确处理 | 检查 catch 块是否有正确的回滚/补偿/通知 |',
    '| "这个问题影响不大" | Judge 不做影响评估，只做事实判定 | 如实报告问题，影响评估留给 approve 阶段 |',
    '| "上一轮已经改进了" | 每轮独立评审，不考虑历史改进 | 只看当前版本的产物质量 |',
    "",
    "**核心原则**：宁可多报不可漏报（FN 比 FP 更严重）。如果犹豫是否扣分，扣。",
    "",
]
