#!/usr/bin/env python3
"""Parse image assets into requirement semantics (optional VLM backend).

Input sources:
- asset_manifest.json generated by feishu_direct_ingest.py
- or a local assets directory

Outputs:
- image_semantics.json
- image_semantics.md
- details/*.md (per-image analysis)
"""

from __future__ import annotations

import contextlib
import re
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from dqg.constants import (
    IMAGE_DEEP_READ_KEYWORDS,
    IMAGE_SIZE_LIGHT_THRESHOLD,
    IMAGE_SIZE_SKIP_THRESHOLD,
)
from dqg.json_utils import load_json, load_json_strict

SUPPORTED_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}


def info(msg: str) -> None:
    print(f"[parse_image_assets] {msg}")


def warn(msg: str) -> None:
    print(f"[parse_image_assets][WARN] {msg}", file=sys.stderr)


def load_prompt(prompt_path: Path | None) -> str:
    default_prompt = (
        "你是需求评审语义抽取助手。请只基于图片内容输出：\n"
        "1) 图片类型（流程图/状态图/页面原型/接口表/其他）\n"
        "2) 可验证的业务语义规则（按条列出，避免笼统描述）\n"
        "3) 与需求评审相关的风险提示\n"
        "4) PRD明显缺口（GAP）与待确认项（OPEN）\n"
        "5) 如果是流程图或状态图，请额外输出：\n"
        "   a) 完整的 Mermaid 代码（用 ```mermaid 包裹）\n"
        "   b) 节点总数（node_count: N）\n"
        "   c) 边/转换总数（edge_count: M）\n"
        "注意：当前属于产品需求阶段，不要输出UT/EUT内容。\n"
        "输出中文。"
    )
    if not prompt_path:
        return default_prompt
    if not prompt_path.exists():
        warn(f"提示词文件不存在，使用默认提示词: {prompt_path}")
        return default_prompt
    text = prompt_path.read_text(encoding="utf-8").strip()
    return text if text else default_prompt


def discover_from_manifest(
    manifest_path: Path,
    browser_manifest_path: Path | None = None,
) -> list[dict[str, Any]]:
    data = load_json_strict(manifest_path)
    if not isinstance(data, list):
        raise ValueError(f"manifest 结构非法，期望 list: {manifest_path}")

    # 加载 browser_asset_manifest 获取 size 信息
    size_map: dict[str, int] = {}
    if browser_manifest_path and browser_manifest_path.exists():
        browser_data = load_json(browser_manifest_path)
        if isinstance(browser_data, list):
            for row in browser_data:
                fname = row.get("filename", "")
                sz = row.get("size", 0)
                if fname and isinstance(sz, int):
                    size_map[fname] = sz
    elif browser_manifest_path is None:
        # 自动探测：同目录下的 browser_asset_manifest.json
        auto_path = manifest_path.parent / "browser_asset_manifest.json"
        if auto_path.exists():
            browser_data = load_json(auto_path)
            if isinstance(browser_data, list):
                for row in browser_data:
                    fname = row.get("filename", "")
                    sz = row.get("size", 0)
                    if fname and isinstance(sz, int):
                        size_map[fname] = sz

    assets: list[dict[str, Any]] = []
    skipped_small = 0
    for row in data:
        path = str(row.get("path", "") or "")
        p = Path(path) if path else None
        if not p or not p.exists() or p.suffix.lower() not in SUPPORTED_EXTS:
            continue

        # size 过滤：优先用 browser manifest 的 size，fallback 到文件系统
        file_size = size_map.get(p.name, 0) or (p.stat().st_size if p.exists() else 0)

        if file_size < IMAGE_SIZE_SKIP_THRESHOLD:
            skipped_small += 1
            continue

        assets.append(
            {
                "kind": row.get("kind", "image"),
                "token": row.get("token", ""),
                "name": row.get("name", ""),
                "section_path": row.get("section_path", ""),
                "path": str(p.resolve()),
                "status": row.get("status", ""),
                "source_block_ids": row.get("source_block_ids", []),
                "file_size": file_size,
            }
        )

    if skipped_small:
        info(f"跳过 {skipped_small} 张小图（<{IMAGE_SIZE_SKIP_THRESHOLD // 1000}KB）")

    return assets


def discover_from_dir(assets_dir: Path) -> list[dict[str, Any]]:
    assets: list[dict[str, Any]] = []
    for p in sorted(assets_dir.rglob("*")):
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS:
            assets.append(
                {
                    "kind": "image",
                    "token": p.stem,
                    "name": p.name,
                    "section_path": "",
                    "path": str(p.resolve()),
                    "status": "local",
                    "source_block_ids": [],
                    "file_size": p.stat().st_size,
                }
            )
    return assets


def sanitize_filename(raw: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", raw).strip("._")
    return value or "asset"


def maybe_load_dashscope(api_key: str) -> Any | None:
    """Deprecated: 保留向后兼容。新代码请用 vlm.provider.get_vlm_provider()。"""
    try:
        import dashscope  # type: ignore[import-untyped]

        dashscope.api_key = api_key
        return dashscope
    except Exception:
        return None


def call_dashscope(
    dashscope: Any,
    image_path: Path,
    prompt: str,
    model: str,
    timeout: int,
) -> str:
    """Deprecated: 保留向后兼容。新代码请用 DashScopeProvider。"""
    from dqg.media.vlm.dashscope_provider import _call_via_sdk

    return _call_via_sdk(dashscope, image_path, prompt, model, timeout)


def summarize(text: str, max_len: int = 160) -> str:
    s = re.sub(r"\s+", " ", text).strip()
    if len(s) <= max_len:
        return s
    return s[: max_len - 3] + "..."


def _load_existing_cache(cache_path: Path) -> dict[str, dict[str, Any]]:
    """加载已有的图片语义缓存，按 token 索引."""
    if not cache_path.exists():
        return {}
    data = load_json(cache_path)
    if data is None:
        return {}
    items = data.get("items", []) if isinstance(data, dict) else []
    return {item["token"]: item for item in items if item.get("token") and item.get("status") == "ok"}


def _classify_image_tier(asset: dict[str, Any]) -> str:
    """根据 size 和 kind 判断图片处理层级.

    Returns:
        "skip": 太小，不值得 VLM 解析
        "light": 轻量描述（UI 截图等，语义已在 PRD 文本中）
        "deep": 精读（流程图/状态机/架构图，需要提取 Mermaid）
    """
    file_size = asset.get("file_size") or 0
    if not file_size and asset.get("path"):
        with contextlib.suppress(OSError):
            file_size = Path(asset["path"]).stat().st_size
    if file_size < IMAGE_SIZE_SKIP_THRESHOLD:
        return "skip"

    # kind 或 section_path 包含流程图/状态机关键词 → deep
    kind = (asset.get("kind", "") or "").lower()
    section = (asset.get("section_path", "") or "").lower()
    name = (asset.get("name", "") or "").lower()
    combined = f"{kind} {section} {name}"
    for kw in IMAGE_DEEP_READ_KEYWORDS:
        if kw.lower() in combined:
            return "deep"

    # 大图更可能是流程图/架构图
    if file_size > IMAGE_SIZE_LIGHT_THRESHOLD:
        return "deep"

    return "light"


LIGHT_PROMPT = "这是一张 UI 截图或页面原型。请用一句话描述其主要内容和用途，不需要详细分析。输出中文。"


def _analyze_single(
    idx: int,
    asset: dict[str, Any],
    vlm_provider: Any | None,
    prompt: str,
    model: str,
    timeout: int,
) -> dict[str, Any]:
    """解析单张图片（线程安全，供并发调用）.

    vlm_provider: VlmProvider 实例或旧版 dashscope 模块（向后兼容）。
    """
    image_path = Path(asset["path"])
    token = asset.get("token", "")
    tier = _classify_image_tier(asset)

    row = {
        "index": idx,
        "kind": asset.get("kind", "image"),
        "token": token,
        "name": asset.get("name", ""),
        "section_path": asset.get("section_path", ""),
        "path": str(image_path),
        "backend": "none",
        "status": "pending",
        "analysis": "",
        "summary": "",
        "error": "",
        "cached": False,
        "tier": tier,
        "file_size": asset.get("file_size") or 0,
    }

    # VLM Provider
    if vlm_provider is not None:
        backend_name = getattr(vlm_provider, "backend_name", "dashscope")
        effective_prompt = LIGHT_PROMPT if tier == "light" else prompt
        try:
            # deep tier（流程图/状态机）先裁剪空白，避免 VLM 压缩后丢失内容
            vlm_image_path = image_path
            if tier == "deep":
                try:
                    from dqg.media.image_preprocess import crop_whitespace

                    cropped_bytes = crop_whitespace(image_path)
                    if cropped_bytes:
                        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                            tmp.write(cropped_bytes)
                            vlm_image_path = Path(tmp.name)
                except Exception:
                    pass

            if hasattr(vlm_provider, "analyze_image"):
                text = vlm_provider.analyze_image(vlm_image_path, effective_prompt)
            else:
                text = call_dashscope(
                    dashscope=vlm_provider,
                    image_path=vlm_image_path,
                    prompt=effective_prompt,
                    model=model,
                    timeout=timeout,
                )

            if vlm_image_path != image_path:
                with contextlib.suppress(OSError):
                    vlm_image_path.unlink()
            row["status"] = "ok"
            row["backend"] = backend_name
            row["analysis"] = text
            row["summary"] = summarize(text)
            return row
        except Exception as exc:
            row["error"] = str(exc)

    # Layer 3: fallback to manual
    ocr_partial = row.pop("_ocr_partial", "")
    if ocr_partial:
        row["status"] = "ok"
        row["backend"] = "ocr:partial"
        row["analysis"] = ocr_partial
        row["summary"] = summarize(ocr_partial)
    else:
        row["status"] = "manual_review_required"
        row["analysis"] = "未启用 VLM 解析。请人工确认该图片中的业务语义，并补充到 SE/REQ/BR 映射与 GAP/OPEN。"
        row["summary"] = "未解析，需人工补录语义"

    return row


def analyze_assets(
    assets: list[dict[str, Any]],
    backend: str,
    prompt: str,
    model: str,
    timeout: int,
    api_key: str,
    cache_path: Path | None = None,
    max_workers: int = 5,
) -> list[dict[str, Any]]:
    vlm_provider = None

    if backend != "none":
        from dqg.media.vlm.provider import get_vlm_provider

        vlm_provider = get_vlm_provider(backend=backend, api_key=api_key, model=model, timeout=timeout)

        if vlm_provider is None and backend == "dashscope":
            warn("未配置 DashScope API Key，降级为 no-vlm")

    # 加载已有缓存，跳过已解析的图片
    cache = _load_existing_cache(cache_path) if cache_path else {}
    cache_hits = 0

    # 分离缓存命中和待解析的图片
    results_map: dict[int, dict[str, Any]] = {}
    pending: list[tuple[int, dict[str, Any]]] = []

    for idx, asset in enumerate(assets, start=1):
        token = asset.get("token", "")
        if token and token in cache:
            cached = cache[token]
            results_map[idx] = {
                "index": idx,
                "kind": asset.get("kind", "image"),
                "token": token,
                "name": asset.get("name", ""),
                "section_path": asset.get("section_path", ""),
                "path": asset.get("path", ""),
                "backend": cached.get("backend", "cached"),
                "status": "ok",
                "analysis": cached.get("analysis", ""),
                "summary": cached.get("summary", ""),
                "error": "",
                "cached": True,
            }
            cache_hits += 1
        else:
            pending.append((idx, asset))

    if cache_hits:
        info(f"缓存命中 {cache_hits}/{len(assets)} 张图片，跳过重复解析")

    # 并发解析待处理图片
    if pending:
        effective_workers = min(max_workers, len(pending))
        if effective_workers > 1 and vlm_provider:
            tier_counts = {"light": 0, "deep": 0}
            for _, asset in pending:
                t = _classify_image_tier(asset)
                if t in tier_counts:
                    tier_counts[t] += 1
            info(
                f"并发解析 {len(pending)} 张图片（{effective_workers} workers, "
                f"deep={tier_counts['deep']}, light={tier_counts['light']}）"
            )

        with ThreadPoolExecutor(max_workers=effective_workers) as executor:
            future_to_idx = {
                executor.submit(_analyze_single, idx, asset, vlm_provider, prompt, model, timeout): idx
                for idx, asset in pending
            }
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                try:
                    row = future.result()
                    results_map[idx] = row
                    status = row.get("status", "")
                    if status == "ok":
                        info(f"  [{idx}/{len(assets)}] ✓ {row.get('token', '')[:12]}")
                    elif status == "failed":
                        warn(f"  [{idx}/{len(assets)}] ✗ {row.get('error', '')[:60]}")
                except Exception as exc:
                    results_map[idx] = {
                        "index": idx,
                        "kind": "image",
                        "token": "",
                        "status": "failed",
                        "error": str(exc),
                        "cached": False,
                    }

    # 按原始顺序返回
    return [results_map[i] for i in sorted(results_map.keys())]


# ---------------------------------------------------------------------------
# Backward-compat re-export: CLI + output writing moved to parse_images_cli.py
# Lazy import to break parse_images ↔ parse_images_cli cycle
# ---------------------------------------------------------------------------


def __getattr__(name: str):
    if name in ("main", "write_outputs"):
        from dqg.media import parse_images_cli

        return getattr(parse_images_cli, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


if __name__ == "__main__":
    raise SystemExit(main())  # noqa: F821  # main is loaded lazily via __getattr__
