#!/usr/bin/env python3
"""Parse image assets into requirement semantics (optional VLM backend).

Input sources:
- asset_manifest.json generated by feishu_direct_ingest.py
- or a local assets directory

Outputs:
- image_semantics.json
- image_semantics.md
- details/*.md (per-image analysis)
"""

from __future__ import annotations

import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from dqg.json_utils import load_json, load_json_strict

SUPPORTED_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}


def info(msg: str) -> None:
    print(f"[parse_image_assets] {msg}")


def warn(msg: str) -> None:
    print(f"[parse_image_assets][WARN] {msg}", file=sys.stderr)


def load_prompt(prompt_path: Path | None) -> str:
    default_prompt = (
        "你是需求评审语义抽取助手。请只基于图片内容输出：\n"
        "1) 图片类型（流程图/状态图/页面原型/接口表/其他）\n"
        "2) 可验证的业务语义规则（按条列出，避免笼统描述）\n"
        "3) 与需求评审相关的风险提示\n"
        "4) PRD明显缺口（GAP）与待确认项（OPEN）\n"
        "5) 如果是流程图或状态图，请额外输出：\n"
        "   a) 完整的 Mermaid 代码（用 ```mermaid 包裹）\n"
        "   b) 节点总数（node_count: N）\n"
        "   c) 边/转换总数（edge_count: M）\n"
        "注意：当前属于产品需求阶段，不要输出UT/EUT内容。\n"
        "输出中文。"
    )
    if not prompt_path:
        return default_prompt
    if not prompt_path.exists():
        warn(f"提示词文件不存在，使用默认提示词: {prompt_path}")
        return default_prompt
    text = prompt_path.read_text(encoding="utf-8").strip()
    return text if text else default_prompt


def discover_from_manifest(manifest_path: Path) -> list[dict[str, Any]]:
    data = load_json_strict(manifest_path)
    if not isinstance(data, list):
        raise ValueError(f"manifest 结构非法，期望 list: {manifest_path}")

    assets: list[dict[str, Any]] = []
    for row in data:
        path = str(row.get("path", "") or "")
        p = Path(path) if path else None
        if not p or not p.exists() or p.suffix.lower() not in SUPPORTED_EXTS:
            continue
        assets.append(
            {
                "kind": row.get("kind", "image"),
                "token": row.get("token", ""),
                "name": row.get("name", ""),
                "section_path": row.get("section_path", ""),
                "path": str(p.resolve()),
                "status": row.get("status", ""),
                "source_block_ids": row.get("source_block_ids", []),
            }
        )
    return assets


def discover_from_dir(assets_dir: Path) -> list[dict[str, Any]]:
    assets: list[dict[str, Any]] = []
    for p in sorted(assets_dir.rglob("*")):
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS:
            assets.append(
                {
                    "kind": "image",
                    "token": p.stem,
                    "name": p.name,
                    "section_path": "",
                    "path": str(p.resolve()),
                    "status": "local",
                    "source_block_ids": [],
                }
            )
    return assets


def sanitize_filename(raw: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", raw).strip("._")
    return value or "asset"


def maybe_load_dashscope(api_key: str) -> Any | None:
    try:
        import dashscope  # type: ignore

        dashscope.api_key = api_key
        return dashscope
    except Exception:
        return None


def call_dashscope(
    dashscope: Any,
    image_path: Path,
    prompt: str,
    model: str,
    timeout: int,
) -> str:
    response = dashscope.MultiModalConversation.call(
        model=model,
        messages=[
            {
                "role": "user",
                "content": [
                    {"image": str(image_path)},
                    {"text": prompt},
                ],
            }
        ],
        timeout=timeout,
    )

    if getattr(response, "status_code", None) != 200:
        code = getattr(response, "code", "unknown")
        msg = getattr(response, "message", "unknown error")
        raise RuntimeError(f"DashScope 调用失败: code={code}, message={msg}")

    output = response.output if hasattr(response, "output") else {}
    choices = output.get("choices", []) if isinstance(output, dict) else []
    if not choices:
        raise RuntimeError("DashScope 返回内容为空")

    message = choices[0].get("message", {})
    content = message.get("content", [])
    if isinstance(content, list):
        text_parts: list[str] = []
        for item in content:
            if isinstance(item, dict) and item.get("text"):
                text_parts.append(str(item.get("text")))
        result = "\n".join(text_parts).strip()
        if result:
            return result

    # fallback
    text = choices[0].get("text") or ""
    if text:
        return str(text)

    raise RuntimeError("无法解析 DashScope 返回文本")


def summarize(text: str, max_len: int = 160) -> str:
    s = re.sub(r"\s+", " ", text).strip()
    if len(s) <= max_len:
        return s
    return s[: max_len - 3] + "..."


def _load_existing_cache(cache_path: Path) -> dict[str, dict[str, Any]]:
    """加载已有的图片语义缓存，按 token 索引."""
    if not cache_path.exists():
        return {}
    data = load_json(cache_path)
    if data is None:
        return {}
    items = data.get("items", []) if isinstance(data, dict) else []
    return {item["token"]: item for item in items if item.get("token") and item.get("status") == "ok"}


def _analyze_single(
    idx: int,
    asset: dict[str, Any],
    dashscope: Any | None,
    prompt: str,
    model: str,
    timeout: int,
) -> dict[str, Any]:
    """解析单张图片（线程安全，供并发调用）."""
    image_path = Path(asset["path"])
    token = asset.get("token", "")
    row = {
        "index": idx,
        "kind": asset.get("kind", "image"),
        "token": token,
        "name": asset.get("name", ""),
        "section_path": asset.get("section_path", ""),
        "path": str(image_path),
        "backend": "dashscope" if dashscope else "none",
        "status": "pending",
        "analysis": "",
        "summary": "",
        "error": "",
        "cached": False,
    }

    if dashscope is not None:
        try:
            text = call_dashscope(
                dashscope=dashscope,
                image_path=image_path,
                prompt=prompt,
                model=model,
                timeout=timeout,
            )
            row["status"] = "ok"
            row["analysis"] = text
            row["summary"] = summarize(text)
        except Exception as exc:
            row["status"] = "failed"
            row["error"] = str(exc)
    else:
        row["status"] = "manual_review_required"
        row["analysis"] = (
            "未启用 VLM 解析。请人工确认该图片中的业务语义，"
            "并补充到 SE/REQ/BR 映射与 GAP/OPEN。"
        )
        row["summary"] = "未解析，需人工补录语义"

    return row


def analyze_assets(
    assets: list[dict[str, Any]],
    backend: str,
    prompt: str,
    model: str,
    timeout: int,
    api_key: str,
    cache_path: Path | None = None,
    max_workers: int = 5,
) -> list[dict[str, Any]]:
    use_dashscope = False
    dashscope = None

    if backend in {"auto", "dashscope"}:
        if api_key:
            dashscope = maybe_load_dashscope(api_key)
            use_dashscope = dashscope is not None
        elif backend == "dashscope":
            warn("未配置 DashScope API Key，降级为 no-vlm")

    if backend == "none":
        use_dashscope = False

    # 加载已有缓存，跳过已解析的图片
    cache = _load_existing_cache(cache_path) if cache_path else {}
    cache_hits = 0

    # 分离缓存命中和待解析的图片
    results_map: dict[int, dict[str, Any]] = {}
    pending: list[tuple[int, dict[str, Any]]] = []

    for idx, asset in enumerate(assets, start=1):
        token = asset.get("token", "")
        if token and token in cache:
            cached = cache[token]
            results_map[idx] = {
                "index": idx,
                "kind": asset.get("kind", "image"),
                "token": token,
                "name": asset.get("name", ""),
                "section_path": asset.get("section_path", ""),
                "path": asset.get("path", ""),
                "backend": cached.get("backend", "cached"),
                "status": "ok",
                "analysis": cached.get("analysis", ""),
                "summary": cached.get("summary", ""),
                "error": "",
                "cached": True,
            }
            cache_hits += 1
        else:
            pending.append((idx, asset))

    if cache_hits:
        info(f"缓存命中 {cache_hits}/{len(assets)} 张图片，跳过重复解析")

    # 并发解析待处理图片
    if pending:
        ds = dashscope if use_dashscope else None
        effective_workers = min(max_workers, len(pending))
        if effective_workers > 1 and ds:
            info(f"并发解析 {len(pending)} 张图片（{effective_workers} workers）")

        with ThreadPoolExecutor(max_workers=effective_workers) as executor:
            future_to_idx = {
                executor.submit(
                    _analyze_single, idx, asset, ds, prompt, model, timeout
                ): idx
                for idx, asset in pending
            }
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                try:
                    row = future.result()
                    results_map[idx] = row
                    status = row.get("status", "")
                    if status == "ok":
                        info(f"  [{idx}/{len(assets)}] ✓ {row.get('token', '')[:12]}")
                    elif status == "failed":
                        warn(f"  [{idx}/{len(assets)}] ✗ {row.get('error', '')[:60]}")
                except Exception as exc:
                    results_map[idx] = {
                        "index": idx,
                        "kind": "image",
                        "token": "",
                        "status": "failed",
                        "error": str(exc),
                        "cached": False,
                    }

    # 按原始顺序返回
    return [results_map[i] for i in sorted(results_map.keys())]


# ---------------------------------------------------------------------------
# Backward-compat re-export: CLI + output writing moved to parse_images_cli.py
# ---------------------------------------------------------------------------
from dqg.media.parse_images_cli import main, write_outputs  # noqa: F401


if __name__ == "__main__":
    raise SystemExit(main())
